# Generated by Django 2.2.9 on 2021-02-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_auto_20210216_1002"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(),
        ),
    ]
