# Generated by Django 2.2.6 on 2021-03-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_auto_20210216_1535"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(
                error_messages={"blank": "Введите хоть что-нибудь!"}
            ),
        ),
    ]
