# Generated by Django 2.2.6 on 2021-03-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_auto_20210304_0543"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.CharField(max_length=1000),
        ),
    ]
