# Generated by Django 2.2.6 on 2021-04-05 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20210404_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_id',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile_id',
            name='image_author',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
