# Generated by Django 2.2.6 on 2021-04-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20210405_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_id',
            name='image_author',
            field=models.ImageField(blank=True, default=0, upload_to='users/'),
            preserve_default=False,
        ),
    ]
