# Generated by Django 2.2.6 on 2021-04-06 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20210405_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_id',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
